### ISSUE TITLE
Add Markdown Output Option

### ISSUE THREAD

**Issue by justsml** [antonreshetov/mysigmail#1]
I love this project! Thank you!

I was working on something similar over the holidays: generate author info/bio in markdown based on github username (to be included in README.md - maybe implemented as a git hook).

Would you consider a PR to accommodate this? (if not, I understand)

**Comment by antonreshetov** [comment]
Hi @justsml 
Thank you for your interest. Unfortunately, I don't see the point. The signature generator should generate valid html with inline styles for correct display in various email clients
