### ISSUE TITLE
Job Separator - New Line not working

### ISSUE THREAD

**Issue by rhnvrm** [antonreshetov/mysigmail#13]
![screenshot from 2019-01-08 13-11-55](https://user-images.githubusercontent.com/952036/50816582-00e31a80-1347-11e9-86c2-730855a0a538.png)

**Comment by antonreshetov** [comment]
Hi @rhnvrm 
Thanks for bug. Most likely, this bug occurred during refactoring #11.

**Comment by antonreshetov** [comment]
Closed because it was fixed in #14
