### ISSUE TITLE
gmail base64 image

### ISSUE THREAD

**Issue by numiscorner** [antonreshetov/mysigmail#17]
Hello,

First of all, thank you for this nice project.
I used your tool and I created an email signature with a profile picture.
When I try to use the signature in gmail, I got an error message from gmail. The error indicates that the text is too long. I think it's due to the base64 encoding. Do you have a solution ?

Thank you.

Nicolas

**Comment by antonreshetov** [comment]
Hi @numiscorner.
For a gmail client, signatures with a base64 converted image appear to be too long in some cases. Try using an image link instead of embedding it as base64.

So far I do not know how to solve this problem :(

**Comment by numiscorner** [comment]
Hello @antonreshetov,

Thanks, it solved the problem !
