### ISSUE TITLE
Gmail display

### ISSUE THREAD

**Issue by alineassis** [antonreshetov/mysigmail#3]
Hi,
I'm using Airmail as my main client and inserted the signature there. When sending the message to a gmail account, the image is not displayed and the email has an extra line break:

![screenshot 2019-01-04 17 31 12](https://user-images.githubusercontent.com/5604368/50706983-a4ca7e80-1046-11e9-93cd-8c50d82cb8c1.png)
![screenshot 2019-01-04 17 31 47](https://user-images.githubusercontent.com/5604368/50706989-a98f3280-1046-11e9-870d-e175444d8c71.png)

**Comment by antonreshetov** [comment]
Hi @alineassis 
Unfortunately I don't have an Airmail client to try to reproduce the problem. You also need more information about the problem, such as how you uploaded the image

**Comment by alineassis** [comment]
Hey, I've tried both ways using your website: mysigmail.com
Created the signature there, than Copied into Airmail. The other try was using the HTML. Both gave me the same result sending to Gmail. The image was uploaded in a png format through the website.

**Comment by antonreshetov** [comment]
@alineassis 
It seems that the gmail client does not support base64 pasting through the `background-image`.
It will be necessary to fix it in the future. Now you can solve this problem by add the image link from another source

**Comment by alineassis** [comment]
Got it! I'll try, thanks.
What about the word-break happening on the email address?

**Comment by antonreshetov** [comment]
Generally it is strange why it adds the line break, if it is not there in reality. Could you please send json of your signature?

**Comment by antonreshetov** [comment]
@alineassis i fix the bug to display base64 and i close this issue. If you still have a problem with line break, please open a new issue

**Comment by jkupczak** [comment]
@alineassis 

The unresolved line break issue here can be solved by removing the padding from the `<a>` tag.
