### ISSUE TITLE
Auto-compress images before upload

### ISSUE THREAD

**Issue by mykeels** [antonreshetov/mysigmail#30]
I noticed that the app gives an error when an image to be uploaded has a size of more than 10KB. 

Would it be possible to make sure the app compresses uploaded images automatically, so the user doesn't have to bother with doing that?

A warning could be shown when an image of >10KB is about to be uploaded, and the user given a choice to let the app perform the compression.

**Comment by antonreshetov** [comment]
Hi @mykeels 
The fact is that the application works exclusively in the browser, it has no backend part. To optimize the image you need a backend.

**Comment by mykeels** [comment]
Actually, optimisation can be done in the front-end. 

I could whip up a PR if I'm sure it's something you'd be interested in.

**Comment by antonreshetov** [comment]
You can try to implement

**Comment by antonreshetov** [comment]
@mykeels thanks!

**Comment by antonreshetov** [comment]
Closed because it was done in #34
