### ISSUE TITLE
More templates

### ISSUE THREAD

**Issue by antonreshetov** [antonreshetov/mysigmail#31]
Now I am working on version 2 in which there will be a WYSIWYG email editor.

Therefore, I would be happy if there are willing to help me in the development of templates for signatures in version 1.

**Comment by mclintprojects** [comment]
How would I go about whipping up templates?

**Comment by antonreshetov** [comment]
Hi @mclintprojects 
Many examples of templates can find - https://www.mail-signatures.com/signature-templates

**Comment by mclintprojects** [comment]
Cool. I'll get to work on this!

**Comment by antonreshetov** [comment]
1. Comments do not comply with the [сonvention](https://github.com/antonreshetov/mysigmail/blob/master/.github/COMMIT_CONVENTION.md)
2. You should not use hashtags in commits, as this is a link to issue
3. The templates do not look correct, apparently you have not tested them with different content
4. Template design is questionable
