### ISSUE TITLE
I think this issue still exist, when i copy as select to gmail, the social icons go big.

### ISSUE THREAD

**Issue by iam-rocketman** [antonreshetov/mysigmail#35]
I think this issue still exist, when i copy as select to gmail, the social icons go big. 
<img width="478" alt="screen shot 2019-02-12 at 10 28 25 am" src="https://user-images.githubusercontent.com/768793/52612899-aabb4700-2eb1-11e9-8fee-94ee39f8812c.png">

Above issue is what i am facing, turnaround for this fix to use the backspace twic and icon comes to normal size.

_Originally posted by @iam-rocketman in https://github.com/antonreshetov/mysigmail/issues/2#issuecomment-462617299_

**Comment by antonreshetov** [comment]
Hi @iam-rocketman I think it's the extra blank space after the signature
