### ISSUE TITLE
Add draggable to the form

### ISSUE THREAD

**Issue by champagnepappi** [antonreshetov/mysigmail#40]
Currently if one wants to interchange the order of the field inputs he/she has to delete the 
fields. Draggable will improve the user experience for cases where a user needs to interchange the fields.

**Comment by njbrown** [comment]
I like this idea. It's already being done for the social media links. It would be great seeing it for the other fields.

**Comment by antonreshetov** [comment]
Some default fields depend on the template design, so I didn't develop drag and drop for them

**Comment by champagnepappi** [comment]
@antonreshetov  I thought the fields don't really affect the design but just the order in which they'll appear in the template design
