### ISSUE TITLE
Gmail: "avatar"/broken picture instead of image

### ISSUE THREAD

**Issue by gcjbos** [antonreshetov/mysigmail#42]
After uploading the "copy as select" to Gmail I see an avatar picture instead of the image I uploaded.
![image](https://user-images.githubusercontent.com/6464256/53196887-5a628880-3619-11e9-8dfa-ca705952cee9.png)

**Comment by antonreshetov** [comment]
looks like gmail doesn't support base64 images anymore.
I tried from different sources to put just base64 image and in all cases the image was not shown after saving the signature in gmail web client

**Comment by gcjbos** [comment]
so, what do you recommend to still get the image?

**Comment by antonreshetov** [comment]
Right now, url to your image

**Comment by gcjbos** [comment]
hmm, the social icon doesn't work either.
And that one is through an URL to mysigmail
https://s3.eu-central-1.amazonaws.com/mysigmail/icons/linkedin.png
[image: image.png]
Seems to me that there is a different issue

**Comment by antonreshetov** [comment]
I don't see a problem with icons
![2019-02-22_14-22-28](https://user-images.githubusercontent.com/17480987/53239539-56804600-36ad-11e9-9f6d-cb4d4ec4b964.png)

**Comment by gcjbos** [comment]
it was the Hubspot plugin that caused the issue

**Comment by antonreshetov** [comment]
Closed by #44
