### ISSUE TITLE
Copy as HTML does not work on Firefox

### ISSUE THREAD

**Issue by dsbert** [antonreshetov/mysigmail#46]
Copy as HTML does not work on Firefox

**Comment by antonreshetov** [comment]
Hi @dsbert, what browser version, what mode? Need more information. Since I just I rechecked on Firefox 65.0.1 and everything is fine

**Comment by antonreshetov** [comment]
Closed because it was fixed in f320658b04639e50c1fb0d8544094fb1d3c44010

**Comment by dsbert** [comment]
I use Firefox Nightly and it looks like this feature is working now, thanks @antonreshetov
