### ISSUE TITLE
RFE : Add custom social media option (logo + link)

### ISSUE THREAD

**Issue by MagicFab** [antonreshetov/mysigmail#47]
I noticed Mastodon and diaspora* are missing from social network icons.
It would be useful to be able to specifiy more custom social media as config options and be able to use them in any project.

**Comment by antonreshetov** [comment]
Hi @MagicFab 
Adding custom social icons are not planned as a whole.
With regard to Mastodon and diaspora* maybe i'll add in the future.

**Comment by antonreshetov** [comment]
Closed because it was added in #50
