### ISSUE TITLE
RFE : Enable rectangular area choice when cropping the logo / avatar

### ISSUE THREAD

**Issue by MagicFab** [antonreshetov/mysigmail#48]
When cropping the avatar after choosing an image to upload, the selection can only be square. As a result rectangular logos can't be used. Having the ability to crop a rectangular shape would not affect layout significantly and would make it possible to use most commercial (ractangular, horizontal) logos without modification.

**Comment by antonreshetov** [comment]
This functionality is planned.

**Comment by antonreshetov** [comment]
Closed because it was added in #51
