### ISSUE TITLE
[Feature] RTL Support

### ISSUE THREAD

**Issue by eladcandroid** [antonreshetov/mysigmail#52]
Please add a RTL support (from settings) - Logo on the right side and right-aligned content

**Comment by antonreshetov** [comment]
Hi @eladcandroid
Will it make sense if the labels will still be in English?

**Comment by eladcandroid** [comment]
Hi @antonreshetov 
Of course it would be great if you could edit the labels. 
BTW, your app is really amazing and useful...

**Comment by antonreshetov** [comment]
You can add custom field by press "Add custom fields" and set necessary Label

**Comment by eladcandroid** [comment]
I know, thanks, but it would be nicer to be able edit the current fields

**Comment by antonreshetov** [comment]
Еhe main labels depend on the design of the template, so editing is not provided for them

**Comment by antonreshetov** [comment]
@eladcandroid 
The signature should look like this?
![2019-04-20_07-44-02](https://user-images.githubusercontent.com/17480987/56452863-3df47b00-6340-11e9-9c27-661ea171fd1f.png)
