### ISSUE TITLE
base64 is not compatible with the Outlook desktop client

### ISSUE THREAD

**Issue by jkupczak** [antonreshetov/mysigmail#8]
See here: https://sendgrid.com/blog/embedding-images-emails-facts/

I'd recommend removing this as an option for the user to select. Depending on the industry, Outlook has a large marketshare.

Alternatively you could include some text that highlights this issue so that the user can decide if it's worth it or not for their use case. Say for example, they only email a small handful of people and know that their recipients don't use Outlook.

**Comment by antonreshetov** [comment]
Closed because it was fixed in #22
